server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.220.100:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.220.100:3306/seata_account
    username: root
    password: root
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 192.168.220.100:8091
    enable-degrade: false
    disable-global-transaction: false
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: 192.168.220.100:8848
#      group: SEATA_GROUP
#      userName: ""
#      password: ""
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 192.168.220.100:8848
#      namespace:
#      userName: ""
#      password: ""
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

