###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.220.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true   # 表示注册时使用IP而不是hostname
        enabled: true       # 启用服务发现
        register: true      # 启用服务注册
        deregister: true    # 表示停止时取消注册
        health-check-interval: 10s            # 健康检查频率
        health-check-critical-timeout: 30s    # 健康检查失败多长时间后，取消注册


